version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-webserver:
    hostname: airflow-webserver
    image: my-airflow:2.7.1-java      
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AIRFLOW_ADMIN_USER: ${AIRFLOW_ADMIN_USER}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW_ADMIN_EMAIL: ${AIRFLOW_ADMIN_EMAIL}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__WORKERS: 2
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install -r /requirements.txt && \
        airflow db upgrade && \
        airflow users create \
          --username "$AIRFLOW_ADMIN_USER" \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email "$AIRFLOW_ADMIN_EMAIL" \
          --password "$AIRFLOW_ADMIN_PASSWORD" || true && \
        airflow users list && \
        exec airflow webserver

  airflow-scheduler:
    hostname: airflow-scheduler
    image: my-airflow:2.7.1-java
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
      AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      EXPIRES_AT: ${EXPIRES_AT}
      SCOPE: ${SCOPE}
      AUTHENTICATION_CODE: ${AUTHENTICATION_CODE}
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./requirements.txt:/requirements.txt
      - ./.env:/opt/airflow/.env
      - ./data:/opt/airflow/data
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install --user -r /requirements.txt && \
        exec airflow scheduler

volumes:
  postgres_db:
